//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PohoronnoeBuro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChekProduct
    {
        public int ID_ChekProduct { get; set; }
        public int Product_ID { get; set; }
        public int Info_ID { get; set; }
    
        public virtual Info Info { get; set; }
        public virtual Product Product { get; set; }
    }
}
