//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PohoronnoeBuro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Info()
        {
            this.ChekProduct = new HashSet<ChekProduct>();
        }
    
        public int ID_INFO { get; set; }
        public System.DateTime DateInfo { get; set; }
        public int PaymentMethod_ID { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public int Employees_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChekProduct> ChekProduct { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
