//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PohoronnoeBuro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ChekProduct = new HashSet<ChekProduct>();
        }
    
        public int ID_Product { get; set; }
        public string NameOfProduct { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> InsuranceCompany_ID { get; set; }
        public int ProductCategory_ID { get; set; }
        public int Plot_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChekProduct> ChekProduct { get; set; }
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual Plot Plot { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
